/* eslint-disable import/prefer-default-export */
export const GET_GATEWAY_LIST_SUCCESS = 'GET_GATEWAY_LIST_SUCCESS';
export const GET_GATEWAY_LIST_ISLOADING = 'GET_GATEWAY_LIST_ISLOADING';

// Create gateways
export const CREATE_GATEWAY_SUCCESS = 'CREATE_GATEWAY_SUCCESS';
export const CREATE_GATEWAY_ERROR = 'CREATE_GATEWAY_ERROR';
export const DELETE_CREATE_GATEWAY_ERROR = 'DELETE_CREATE_GATEWAY_ERROR';
export const CREATE_GATEWAY_ERROR_ISLOADING = 'CREATE_GATEWAY_ERROR_ISLOADING';

// create device types
export const CREATE_DEVICE_SUCCESS = 'CREATE_DEVICE_SUCCESS';
export const CREATE_DEVICE_ERROR = 'CREATE_DEVICE_ERROR';
export const DELETE_CREATE_DEVICE_ERROR = 'DELETE_CREATE_DEVICE_ERROR';
export const CREATE_DEVICE_ERROR_ISLOADING = 'CREATE_DEVICE_ERROR_ISLOADING';
export const DELETE_DEVICE = 'DELETE_DEVICE';
export const DELETE_DEVICE_ISLOADING = 'DELETE_DEVICE_ISLOADING';
